export const themeProvider = {
  day: {
    highlightColor: '#2A52E5',
    backgroundColor: '#FFFFFF',
    fontFamily: '\'Inter\', sans-serif',
    fontSize: 16,
    fontColor: '#454545',
    lineColor: '#EDEDED',
    headerColor: '#F6F6F6',
    errorColor: '#E60000',
    successColor: '#2A52E5',
    disableColor: '#CCCCCC',
    shadowColor: '#9E9E9E',
    pinBorderColor: '#999999',
    modalColor: '#ADADAD',
    modalShadow: '#919191',
    modalH2Color: '#656565',
  },
  night: {},
};
